name: my_project
version: 1.0.0
config-version: 2

profile: my_project_profile

# Other configurations...

# Specify the directory where your models are located
model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
